version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: timetable-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: timetable_db
      MYSQL_USER: timetable_user
      MYSQL_PASSWORD: timetable_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - timetable-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: timetable-backend
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: timetable_user
      DB_PASSWORD: timetable_password
      DB_NAME: timetable_db
      PORT: 5000
      NODE_ENV: production
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - timetable-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: timetable-frontend
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - timetable-network

volumes:
  mysql_data:

networks:
  timetable-network:
    driver: bridge